CREATE SEQUENCE IF NOT EXISTS product_sequence  START WITH 101 INCREMENT BY 25;

CREATE SEQUENCE IF NOT EXISTS orders_sequence START WITH 101 INCREMENT BY 25;

CREATE SEQUENCE IF NOT EXISTS users_sequence START WITH 101 INCREMENT BY 25;

CREATE SEQUENCE IF NOT EXISTS stock_sequence START WITH 101 INCREMENT BY 25;








