spring:
  application:
    name: discovery-service
  config:
    import: optional:configserver:http://localhost:8180
  profiles:
    active: dev
  cloud:
    config:
      fail-fast: true
server:
  port: 8761