spring:
  flyway:
    user: postgres
    password: 12345679
    schemas: product-schemas
    url: jdbc:postgresql://localhost:5432/microservice-shop-database
    enabled: true
    locations: filesystem:D:/repos/trainee-repo-YD/migration-service/src/main/resources/migration
    default-schema: product-schemas
    baseline-on-migrate: true
  cloud:
    config:
      import-check:
        enabled: false
      fail-fast: true
  jpa:
    properties:
      hibernate:
        default_schema: product-schemas
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice-shop-database
    username: postgres
    password: 12345679
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8888/realms/services-dev-realm
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/realms/services-dev-realm
server:
  port: 8082