spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8180
  profiles:
    active: dev
server:
  port: 8082
product-service.url: http://localhost:8080
stock-service.url: http://localhost:8081
user-service.url: http://localhost:8082