spring:
  data:
    redis:
      port: 6379
      host: localhost
      database: 0
  cache:
    type: redis
  jpa:
    properties:
      hibernate:
        default_schema: product-schemas
  application:
    name: order-service
  cloud:
    config:
      import-check:
        enabled: false
      fail-fast: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/microservice-shop-database
    username: postgres
    password: 12345679
  flyway:
    user: postgres
    password: 12345679
    schemas: product-schemas
    url: jdbc:postgresql://localhost:5432/microservice-shop-database
    enabled: true
    locations: filesystem:D:/repos/trainee-repo-YD/migration-service/src/main/resources/migration
    default-schema: product-schemas
    baseline-on-migrate: true
server:
  port: 8083

product-service.url: http://localhost:8080
stock-service.url: http://localhost:8081
user-service.url: http://localhost:8082