spring:
  application:
    name: product-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true
  flyway:
    user: postgres
    password: 12345679
    schemas: product-schemas
    url: jdbc:postgresql://localhost:5432/microservice-shop-database
    enabled: true
    locations: classpath:migration
server:
  port: 8080
