spring:
  application:
    name: migration-service
  flyway:
    user: postgres
    password: 12345679
    schemas: product-schemas
    url: jdbc:postgresql://localhost:5432/microservice-shop-database
    enabled: true
    locations: filesystem:D:/repos/trainee-repo-YD/migration-service/src/main/resources/migration
